(define (last-pair items)
  (define (iter seq)
    (let ((head (car seq))
          (tail (cdr seq)))
      (if (null? tail)
          (list head)
          (last-pair tail))))
  (if (null? items)
      (error "Empty list in last-pair")
      (iter items)))
