(define (last-pair items)
  (define (iter input)
    (let ((head (car input))
          (tail (cdr input)))
      (if (null? tail)
          (list head)
          (last-pair tail))))
  (if (null? items)
      (error "Empty list in last-pair")
      (iter items)))
