(load "exercise_2.58.scm")

(define (test-deriv f var)
  (newline)
  (display "f:       ")
  (display f)
  (newline)
  (display "deriv ")
  (display var)
  (display ": ")
  (display (deriv f var))
  (newline))

(test-deriv '(x + 3 * (x + y + 2)) 'x)
(test-deriv '(x + 3 * (x + y + 2)) 'y)
(test-deriv '(x * x) 'x)
(test-deriv '(x * x) 'y)
(test-deriv '(x * x * x + 3 * x) 'x)
(test-deriv '(x * x * x + 3 * x) 'y)
