(define (equal? input1 input2)
  (let ((is-pair-1 (pair? input1))
        (is-pair-2 (pair? input2)))
    (cond ((and (not is-pair-1)
                (not is-pair-2))
           (eq? input1 input2))
          ((and is-pair-1 is-pair-2)
           (and (equal? (car input1)
                        (car input2))
                (equal? (cdr input1)
                        (cdr input2))))
          (else false))))
